### ISSUE TITLE
"missing required module 'sqlite3_ios'" when building unit test

### ISSUE THREAD

**Issue by ijt** [nerdyc/Squeal#28]
When I try to build a unit test that does an import of the whole project, it fails to compile with the error message given in the title. I added $(PROJECT_DIR)/Externals/Squeal/modules to the Swift import paths list, so don't know why this is happening.

**Comment by klaas** [comment]
+1

**Comment by Ealautzenhiser** [comment]
I'm getting the same error.  Do I have to download an SQLite file in addition to Squeal to resolve the error?

**Comment by nerdyc** [comment]
Have you added the import path to your unit test project? Unfortunately, it needs to be added to each target that references the framework.

**Comment by ijt** [comment]
That's probably the issue. I ended up using my own library because I didn't
know how to fix this.
