### ISSUE TITLE
iOS 7 and submitting to the AppStore

### ISSUE THREAD

**Issue by ruslankmlv** [nerdyc/Squeal#31]
Squeal works on iOS 7.1 but won't pass AppStore validator. Any suggestions how to use squeal, so it will pass validator for iOS 7.1.

**Comment by inaoumov** [comment]
I'm interested in using this library in my own project. So I'm interested in finding out if it passes the AppStore validator for iOS 8.

**Comment by ruslankmlv** [comment]
If you're submitting your app only for iOS 8 then it will pass validator without any problems. If you want to submit it for iOS 7, then you have to add files from Squeal folder (Bindable.swift,  Database.swift, DatabasePool.swift, etc) to your project and link libsqlite3.dylib.
