### ISSUE TITLE
Unable to open database file

### ISSUE THREAD

**Issue by inaoumov** [nerdyc/Squeal#32]
I'm creating a DAO class in swift using Squeal, however, when I try to create a database using the example in the documentation, I run into the "unable to open database file" error with SQLite. 

Is there a particular way I am supposed to pass in the file path to the constructor?

**Comment by nerdyc** [comment]
Did you ever resolve this issue? I wasn't able to reproduce it myself.

If so, you can also provide the error: parameter which should describe why the database couldn't be created.

**Comment by tyczj** [comment]
I am having a similar problem, I have a custom init function for a class that makes sure there is a table and database every time an instance it created of that class. in my init method I have the following code

    path = "images.sqlite3"
    var err:NSErrorPointer = nil
    var db = Database(path: path!,error:err) 

db is always nil and err does not report anything back.

all this is being tested on the simulator if that matters any

**Comment by tyczj** [comment]
just doing some more debugging and it must be something with my path because a database get created in memory just fine. does the path have to be something else besides a simple "name.sqlite3"?

**Comment by ijpe** [comment]
I have the similar problem, i use the top code and work fine
