### ISSUE TITLE
Can not use Limit to do pagination

### ISSUE THREAD

**Issue by zhangzhang** [nerdyc/Squeal#33]
When I tried to use Database.selectFrom function and I pass in the Limit parameter, I got an error says "No such function: Optional", then I found in this selectFrom function, the limit was append as "Optional(20)".
My code: 
let rows = db.selectFrom("Merchandise", orderBy: "created desc", offset: start, limit: page, error: &error)
The SQL after parsed:
"SELECT * FROM Merchandise ORDER BY created desc LIMIT Optional(20) OFFSET 0"	
Then I found in line 48 of SelectHelpers.swift, there is a missing "!":
        if limit != nil {
            fragments.append("LIMIT")
            fragments.append("\(limit)")
        }
After I changed it to:
        if limit != nil {
            fragments.append("LIMIT")
            fragments.append("\(limit!)")
        }

It works fine, do you think it is a bug in the code?

Thanks
JJ

**Comment by androidcn** [comment]
try https://github.com/stephencelis/SQLite.swift limit

**Comment by nerdyc** [comment]
Thanks zhangzhang! I fixed the issue and added tests around this part of the code.
