### ISSUE TITLE
follow Installation to install but not work can not import squeal

### ISSUE THREAD

**Issue by androidcn** [nerdyc/Squeal#36]
follow Installation to install but not work, can not import squeal

**Comment by androidcn** [comment]
var error: NSError?
 lazy var db = Database("acc.db3") , error:&error)

'Type' does not have a member named 'error'

**Comment by nerdyc** [comment]
It looks like you've written some invalid Swift. The correct way to initialize the database is:

    Database(path:"acc.db3", error:&error)

Note that it will return an Optional<Database>, so your lazy variable in also optional if it fails.

The tests for this project are a good way to see the library being used.
