### ISSUE TITLE
Problem after upload to testflight (syntax error)

### ISSUE THREAD

**Issue by ijpe** [nerdyc/Squeal#39]
I have an insert into sentence, its 100% functional in develop with xcode, but after that i uploaded to testflight, i received the next error: 
Error Domain=sqlite3 Code=1 "near"=":syntax error"

In my example, the data never have a character "="
I use the same data always

My code is:

var _values = [String: Bindable?]()
                           
                            _values["promotion_id"]                     = json["promotions"][index]["id"].stringValue
                            _values["name"]                             = json["promotions"][index]["name"].stringValue
                            _values["description"]                      = json["promotions"][index]["description"].stringValue
                            _values["image"]                            = json["promotions"][index]["image"].stringValue
                            _values["valid_from"]                       = json["promotions"][index]["valid_from"].stringValue
                            _values["valid_to"]                         = json["promotions"][index]["valid_to"].stringValue
                            _values["restaurant_id"]                    = json["promotions"][index]["restaurant"]["id"].stringValue
                            _values["restaurant_branch_id"]             = json["promotions"][index]["restaurant"]["branch_id"].stringValue
                            _values["restaurant_name"]                  = json["promotions"][index]["restaurant"]["name"].stringValue
                            _values["restaurant_description"]           = json["promotions"][index]["restaurant"]["description"].stringValue
                            _values["restaurant_location_latitude"]     = json["promotions"][index]["restaurant"]["location_latitude"].stringValue
                            _values["restaurant_location_longitude"]    = json["promotions"][index]["restaurant"]["location_longitude"].stringValue
                            _values["restaurant_logo"]                  = json["promotions"][index]["restaurant"]["logo"].stringValue
                            _values["restaurant_cover"]                 = json["promotions"][index]["restaurant"]["cover"].stringValue
                            _values["restaurant_distance"]              = json["promotions"][index]["restaurant"]["distance"].stringValue
                            _values["restaurant_color"]                 = json["promotions"][index]["restaurant"]["color"].stringValue
                            _values["restaurant_open"]                  = json["promotions"][index]["restaurant"]["open"].stringValue
                            _values["restaurant_ticket"]                = json["promotions"][index]["restaurant"]["ticket"].stringValue

                            var error: NSError?
                            self.db.insertInto("promotions", values: _values, error: &error)

**Comment by ijpe** [comment]
My problem persist, with the next code
self.db.insertInto("promotions", columns: ["promotion_id", "name", "description", "image", "restaurant_id", "restaurant_logo", "restaurant_distance"], values: ["1", "nombre", "descripcion", "http://s3.amazonaws.com/.../image.jpg?1410212400", "15", "http://s3.amazonaws.com/...8", "10"], error: &error)

And the problem is after my Archive project in xcode

**Comment by nerdyc** [comment]
I committed some bug fixes to the `insertInto` method around the same time you reported this issue.

Feel free to reopen with additional details if you continued to have this issue. From the description, I have a feeling there was some SQL syntax errors.
