### ISSUE TITLE
Can't put Database in another folder as App

### ISSUE THREAD

**Issue by Stein-Net** [nerdyc/Squeal#46]
I've tried googling this to see if there's a way to do it, but I'm currently trying to make the database for my App in ~/STEiN/(AppName)/(db) - I've tried setting the database string to be the full directory, I've tried making a temporary database, then using system() to move it to where I want it (which got it where I wanted it!) BUT then when I go to use it I keep getting nil. Any help would be greatly appreciated!!

**Comment by cocotutch** [comment]
I encountered this problem too. Basically it's down to the fact that the database files are in the App Bundle. You can't _write_ to there, but you can _read_

A solution is to create a database with "createTable()" function in the App's Documents folder.

**Comment by Stein-Net** [comment]
I actually don't entirely know how to do that x.x Would it be possible for me to store it in their home Directory with the structure I said above using createTable()?  I have other apps that use the ~/STEiN folder which is why I was asking (Maybe I could use system() to move it?)

**Comment by cocotutch** [comment]
@Stein-Net You can definitely do that.

let documentsPath = NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true)[0] as! String

That's the path to the documents directory. You can work it out from there. Append a path component, and then use that as the file location.
