### ISSUE TITLE
Xcode 6.3.1: App using Squeal crashes when run on device, but works in emulator

### ISSUE THREAD

**Issue by alexeyismirnov** [nerdyc/Squeal#48]
Spent a few hours trying to get the app running on my iPad (real device). I was getting a crash when app was trying to load, see the attached image.

![screen shot 2015-05-10 at 4 33 45 pm](https://cloud.githubusercontent.com/assets/4033296/7553576/961b44a4-f732-11e4-9a74-7314d34f2d7c.png)

 Finally was able to get it to work. The solution was to add Squeal for iOS not to Linked Frameworks and Libraries, but rather to Embedded Binaries (in the General section of project settings). Also, setting import module path was not necessary.

Please update installation instructions accordingly. Thanks.

**Comment by muxa** [comment]
I have tried to add Squeal to Embedded Binaries of my project, but it does no add it. Any ideas?
