### ISSUE TITLE
Failed to Code Sign Squeal-iOS

### ISSUE THREAD

**Issue by cornerbodega** [nerdyc/Squeal#49]
Hello,

First off - thank you for making Squeal. I've been working on a relatively simple app that makes heavy use of an existing sqlite database, and I've found Squeal to be very intuitive and fast. 

I'm running into an issue now where I appear to need to be on the Squeal team in order to include the framework as part of my project. When I go to Build Phases -> Embed Frameworks and add Squeal.framework, I am told I need to code sign the Squeal.xcodeproj. When I try to do this, I am told I can't because I am not a part of team D7K65AYKY9. I have tried hitting "Fix Issue" and changing the team and signing types within xcode, but to no avail. I am currently unable to build due to this issue, which I suspect may be related to an update of xcode. I was wondering if this is an issue anyone else is experiencing, or whether anyone has any advice on how I should proceed.

Any help is very much appreciated.

Best,

Marvin 

![screen shot 2015-05-13 at 9 57 41 pm](https://cloud.githubusercontent.com/assets/10392293/7624723/41ccc6c6-f9bb-11e4-90be-81e41211ee68.png)

**Comment by cocotutch** [comment]
I solved this problem by switching the team over.

**Comment by hightekjonathan** [comment]
@cocotutch How did you switch the teams?

**Comment by muxa** [comment]
I'm also having this issue. Any help is appreciated

**Comment by cocotutch** [comment]
Yeah if you open the target and change the Team it can compile.
