### ISSUE TITLE
Swift 2.0 Compatibility

### ISSUE THREAD

**Issue by tyczj** [nerdyc/Squeal#50]
Trying out Xcode 7 and there are a lot of Swift 2.0 compatibility issues, some are easily fixable but others I am not sure what to do.

for example

    public func bindStringValue(stringValue:String, atIndex index:Int, error:NSErrorPointer = nil) -> Bool {
        let cString = stringValue.cStringUsingEncoding(NSUTF8StringEncoding)
        
        let negativeOne = UnsafeMutablePointer<Int>(bitPattern: -1)
        let opaquePointer = COpaquePointer(negativeOne)
        let transient = CFunctionPointer<((UnsafeMutablePointer<()>) -> Void)>(opaquePointer)
        
        let resultCode = sqlite3_bind_text(sqliteStatement, Int32(index), cString!, -1, transient)
        if resultCode != SQLITE_OK {
            if error != nil {
                error.memory = database.sqliteError
            }
            return false
        }
        
        return true
    }

gives an error `CFunctionPointer is unavailable, use a function type @convention(c) (T)->U`

**Comment by appsird** [comment]
Hi Christian,

This appears to be more than can be accomplished with casual edits. I'm hopeful you can rally the internal inertia to push this through the Xcode 7 compiler. Let me know if I can in anyway assist.

**Comment by nerdyc** [comment]
Sure. I'd expected to make much bigger Swift 2.0 changes, but perhaps I can get something that compiles out soon and then slowly update the project later.

**Comment by appsird** [comment]
Hi Christian,

Might toi mâle an initial release thaïs week-end?

Brian

**Comment by nerdyc** [comment]
Working on it now. Hope to also include Carthage support and remove the module map.

**Comment by nerdyc** [comment]
There is now a Swift 2-compatible version in the swift2 branch.

As of today it doesn't support many of the new features of swift 2. For example, throwing errors.

I'll add those soon, but the current commit should more or less work with existing codebases.

**Comment by appsird** [comment]
Thank you,

Will give it a try and get back to you.

Brian

**Comment by ulusoyca** [comment]
Hi,

I can't make query with Swift 2.0 branch:

            let statement = try database.prepareSelectFrom(database.name, columns: nil, whereExpr: "\(COLUMN_MAC) = ?", groupBy: nil, having: nil, orderBy: nil, limit: nil, offset: nil, parameters: ["\(mac)"])

            for row in database.selectFrom(from: String, block: ((Statement)) throws -> T) ) { ..}

What would be the proper way of making a query in Swift 2.0 branch?

Thank you!

**Comment by nerdyc** [comment]
@ulusoyca The for-loop style was removed because it made error handling awkward.

Instead, use a while loop:
```swift
let statement = try database.prepareSelectFrom("people", whereExpr: "email = ?", parameters: [email])
while try statement.next() {
    let personId = statement.int64Value('id')
    // ...
}
```

There's also a helper method that takes a block, and returns an array or whatever you want:

```swift
// returns a [String]
let results = try database.selectFrom("people", columns:["email"]) { $0.stringValueAtIndex(0) ?? "" }
```
