### ISSUE TITLE
Documentation Swift 2

### ISSUE THREAD

**Issue by Robby28** [nerdyc/Squeal#54]
I would like to know , if there is any documentation update for swift 2.0
Are there any informations about how to do the select, insert or update commands, as it is described in the documentation for the previous swift versions
All my commands and connections are no more valid in swift 2.0 and I habe absolutely no idea how to solve that 
It would be so nice to read an updated documentation.
Thanks a lot

**Comment by nerdyc** [comment]
Sorry Robby! I haven't had time to do so, but plan on it this weekend. The changes were more extensive, and the original documentation is hard to keep up-to-date. I'm hoping to trim it down, and move most code to a playground where it can be double-checked with a compiler :)

In the meantime, you can check out the commit history, look at the tests, and also ask some questions here. That might help me figure out what the best things are to document.

You should also look at #53 , which explains how to do a simple SELECT.

**Comment by nerdyc** [comment]
Since keeping the old documentation was worse than useless, I removed it and have replaced it with a playground. I'll work on documentation again at a later time, but for now wanted to avoid confusing people.
