### ISSUE TITLE
Creating Database on Disk Issue 

### ISSUE THREAD

**Issue by TheDoubleD** [nerdyc/Squeal#58]
If I create an in-memory db everything works find. However, when I try to create one on disk I get the error "Instance member 'databaseFile' cannot be used on type 'ViewController'. Any help appreciated!

----- Creating DB in Memory (Works) import UIKit import Squeal

class ViewController: UIViewController {

@IBOutlet weak var enteredURL: UITextField!
@IBOutlet weak var myWebView: UIWebView!

let databaseFile = "myDatabase.db"
let db       = Database() // in-memory db
---- Creating database on Disk will not compile import UIKit import Squeal

class ViewController: UIViewController {

@IBOutlet weak var enteredURL: UITextField!
@IBOutlet weak var myWebView: UIWebView!

let databaseFile = "myDatabase.db"
let db       = Database(path: databaseFile) // on disk db
Compile error is: 'Instance member 'database file' cannot be used on type 'View Controller'

**Comment by nerdyc** [comment]
This is not a Squeal problem. Other instance variables are not accessible in instance variable initializers. Try making db lazy, or initialize db from your init method.
