### ISSUE TITLE
Swift3 under Xcode 8

### ISSUE THREAD

**Issue by Robby28** [nerdyc/Squeal#59]
Apple Releases in XCODE 8 the SWIFT3 language.
Is the actual Squeal program running under Swift 3 , or will there be an update offered ?
Thanks, Robby

**Comment by nerdyc** [comment]
Right now there isnt, but i plan on updating to swift 3 soon. Or you can submit a PR!

**Comment by nerdyc** [comment]
Swift 3 support is now available in master. Those who should like to stay with Swift 2.3 can use the`swift-2.3` branch.
